1. [Linear Regression Using Normal Equation](#Linear-Regression-Using-Normal-Equation)
2. [Detect Overfitting or Underfitting](#Detect-Overfitting-or-Underfitting)
3. [Calculate Mean Absolute Error (MAE)](#calculate-mean-absolute-error-mae)
4. [Calculate Dice Score for Classification](#calculate-dice-score-for-classification)
5. [Calculate Accuracy Score](#calculate-accuracy-score)
6. [Implement Precision Metric](#implement-precision-metric)
7. [Implement F-Score Calculation for Binary Classification](#implement-f-score-calculation-for-binary-classification)
8. [Calculate R-squared for Regression Analysis](#calculate-r-squared-for-regression-analysis)

In [1]:
import numpy as np

### Linear Regression Using Normal Equation

In [2]:
# Test case from DeepML

X = [[1, 1], [1, 2], [1, 3]], 
y = [1, 2, 3]

# Passing them into Numpy array format

X = np.array(X).squeeze()
y = np.array(y)

print(X.shape, y.shape)
print(y)
print(X)

(3, 2) (3,)
[1 2 3]
[[1 1]
 [1 2]
 [1 3]]


In [3]:
# Removing bias column and treating this as simple linear regression 

X = X[:, 1]

''' 
For calculating slope and intercept we need to implement following equation:

    m = (Σ(X - X̄)(Y - Ȳ)) / (Σ(X - X̄)²)
    c = Ȳ - mX̄

And we need to run those equations for every data point and then can be achieved through loop 

'''

class LinearRegression:

    def __init__(self):

        self.coef_ = None
        self.intercept_ = None 

    def fit(self, X, y):

        X_mean = X.mean()
        y_mean = y.mean()

        num = 0
        den = 0

        for i in range(X.shape[0]):
            num = num + (X[i] - X_mean) * (y[i] - y_mean)
            den = den + (X[i] - X_mean) * (X[i] - X_mean)

        self.coef_ = num/den
        self.intercept_ = y.mean() - (self.coef_ * X.mean())

        return self.intercept_, self.coef_
    

lr = LinearRegression()
list(lr.fit(X, y))

[0.0, 1.0]

Normal Equation (Multilinear Regression)

The coefficients are computed as $\theta = (X^\top X)^{-1} X^\top y$.


In [4]:
# __Now considering that bias columns__

X = [[1, 1], [1, 2], [1, 3]], 
y = [1, 2, 3]


def linear_regression_normal_equation(X: list[list[float]], y: list[float]) -> list[float]:

	''' 
	In this case we are gonna implement above formula 
	 '''

	X = np.array(X).squeeze()
	y = np.array(y)

	theta = np.linalg.inv(np.dot(X.T, X)).dot(X.T).dot(y)

	return np.round(theta, 4)

linear_regression_normal_equation(X, y)

array([-0.,  1.])

-----

### Detect Overfitting or Underfitting

In [5]:
training_accuracy = 0.95 
test_accuracy = 0.65

def isit_fit(X,y):

    if (X < 0.7) & (y < 0.7):
        print('Underfitting')
    elif (X - y) > 0.2:
        print('Overfitting')
    else:
        print('Nothing')

isit_fit(training_accuracy, test_accuracy)

Overfitting


---

### Calculate Mean Absolute Error (MAE)

In [6]:
import numpy as np

y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])


print(y_true)
print(y_pred)



[ 3.  -0.5  2.   7. ]
[2.5 0.  2.  8. ]


![](https://miro.medium.com/v2/resize:fit:1400/format:webp/1*0j3BZ0lPRX86aTjLWDnhwQ.png)

In [7]:
sum = 0
count = 0
for i in range(len(y_true)):
    sum += abs(y_true[i] - y_pred[i])
    count += 1

print(sum/len(y_true))
print(sum, count, sum/count)

0.5
2.0 4 0.5


In [8]:
# 2D Matrix 

X = np.array([[0.5, 1], [-1, 1], [7, -6]])
y = np.array([[0, 2], [-1, 2], [8, -5]])


print(X)
print(y)

[[ 0.5  1. ]
 [-1.   1. ]
 [ 7.  -6. ]]
[[ 0  2]
 [-1  2]
 [ 8 -5]]


In [9]:
# We have to get this 

print(abs(0.5 - 0) + abs(1-2) + abs(-1 + 1) + abs(2 - 1) + abs(7-8) + abs(-6 + 5))

4.5


In [10]:
total = 0
count = 0

for i in range(len(X)):
    for j in range(len(X[0])):
        total += abs(X[i][j] - y[i][j])
        count +=1 

print(total)
print(count)

total/count

4.5
6


0.75

In [11]:
# __Logic for working both 1D and 2D array__

def get_mae(X, y):

    sum = 0
    count = 0

    if X.ndim == 1:
          for i in range(len(X)):
                sum += abs(X[i] - y[i])
                count += 1
    else:
         for i in range(len(X)):
              for j in range(len(X[0])):
                   sum += abs(X[i][j] - y[i][j])
                   count +=1 
    return round((sum/count), 3)

print(get_mae(X, y))
print(get_mae(y_true, y_pred))

0.75
0.5


----

### Calculate Dice Score for Classification

Especially useful when:

- Data is highly imbalanced
- Positive class is rare
- Pixel-wise prediction is required


$$
\text{Dice} = \frac{2|A \cap B|}{|A| + |B|}
$$

 Dice focuses on correct positives, not majority class.

In [ ]:
'''
The Dice Score is used to measure the similarity between two sets and is particularly useful in tasks like 
image segmentation and binary classification. 
'''

import numpy as np

y_true = np.array([1, 1, 0, 1, 0, 1])
y_pred = np.array([1, 1, 0, 0, 0, 1])

y_true * y_pred

array([1, 1, 0, 0, 0, 1])

In [12]:
def dice_score(y_true, y_pred):
    
    if np.sum(y_true) > 0:
        res =(2 * np.sum(y_pred & y_true)) / (np.sum(y_true) + np.sum(y_pred))
    else:
        res = 0.0
        
    return round(res, 3)

dice_score(y_true, y_pred)

0.857

----

### Calculate Accuracy Score

In [5]:
import numpy as np 

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 0, 1, 0, 1])

5/6


sum(y_true == y_pred)/len(y_true)

0.8333333333333334

### Implement Precision Metric

In [5]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])

y_true, y_pred

(array([1, 0, 1, 1, 0, 1]), array([1, 0, 1, 0, 0, 1]))

Precision = TP / (TP + FP)

- TP -> Actual class is postivie (1) and model predicted positive (1) as well
- FP -> Actual class is negative (0) but model predicted as positive (1)

In [ ]:
TP = 0
FP = 0

for true, pred in zip(y_true, y_pred):
    if true == 1 and pred == 1:
        TP += 1
    elif true == 0 and pred == 1:
        FP += 1
    else:
        pass


print(TP, FP)

3 0


----

### Implement F-Score Calculation for Binary Classification

The F-Score combines both Precision and Recall into a single metric, providing a balanced measure of a model's performance.

It is a measure of predictive performance that's calculated from the Precision and Recall metrics.

In [2]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])

beta = 1 # A float value that adjusts the importance of Precision and Recall. When beta=1, it computes the F1-Score, a balanced measure of both Precision and Recall.

![](https://www.gstatic.com/education/formulas2/553212783/en/f1_score.svg)

In [ ]:
# F1 = TP / (TP + 0.5 * (FP + FN))

# - TP -> Actual class is postivie (1) and model predicted positive (1) as well
# - FP -> Actual class is negative (0) but model predicted as positive (1)
# - FN -> Actual class is positive (1) but model predicted as negative (0)


TP = 0
FP = 0
FN = 0

for true, pred in zip(y_true, y_pred):
    if true == 1 and pred == 1:
        TP += 1
    elif true == 0 and pred == 1:
        FP += 1
    elif true == 1 and pred == 0:
        FN += 1
    else:
        pass

print(TP, FP, FN)

3 0 1


In [5]:
F1 = round(TP / (TP + 0.5 * (FP + FN)), 3)
F1

0.857

__With beta__

$$
F_\beta = \frac{(1+\beta^2)\,(\text{precision} \times \text{recall})}{\beta^2 \times \text{precision} + \text{recall}}
$$



- Recall: The number of true positive results divided by the number of all samples that should have been identified as positive.
- Precision: The number of true positive results divided by the number of all samples predicted to be positive, including those not identified correctly.


In [27]:
# Using Beta value formula 

y_true = np.array([1, 0, 1, 1, 0, 0]) 
y_pred = np.array([1, 0, 0, 0, 0, 1]) 
beta = 1 


TP = 0
FP = 0
FN = 0

for true, pred in zip(y_true, y_pred):
    if true == 1 and pred == 1:
        TP += 1
    elif true == 0 and pred == 1:
        FP += 1
    elif true == 1 and pred == 0:
        FN += 1
    else:
        pass


recall    = TP / (TP + FN)
precision = TP / (TP + FP)

print(TP, FP, FN, recall, precision)

F1_beta = ((1 + beta ** 2) * (precision * recall)) / (((beta ** 2) * precision) + recall) 

round(F1_beta, 3)

1 1 2 0.3333333333333333 0.5


0.4

----

### Calculate R-squared for Regression Analysis

R-squared, also known as the coefficient of determination, is a measure that indicates how well the independent variables explain the variability of the dependent variable in a regression model.

R2 = 1 - (SS_res / SS_tot)

* SS_res =  (Residual Sum of Squares): Measures the variation in the dependent variable that is not explained by the model.
* SS_total = (Total Sum of Squares): Measures the total variation in the dependent variable

__Calculation Steps__

1. Calculate the Mean: Find the mean of the observed values of the dependent variable. 
2. Calculate Total Variation: SS_tot ​= ∑(yi​−yˉ​)^2
            :-         Where yi​ is each observed value and yˉ​ is the mean of observed values.
3. Calculate Residual Variation: SS_res ​= ∑(yi​−y^​i​)^2
            :-         Where y^​i​ is the predicted value from the regression model.
4. Apply the R-squared Formula: Substitute the calculated values into the R-squared formula.



In [48]:
import numpy as np 

In [47]:
%%time

y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 2.1, 2.9, 4.2, 4.8])


mean_ = np.average(y_true)
SS_res = sum([(i-j)**2 for i, j in zip(y_true, y_pred)])
SS_total = sum([(i-mean_)**2 for i in y_true])

r2 = 1 - (SS_res / SS_total)


print(r2, SS_res, SS_total, mean_)

0.989 0.11000000000000018 10.0 3.0
CPU times: user 128 μs, sys: 27 μs, total: 155 μs
Wall time: 155 μs


In [46]:
%%time

# Using Pure Numpy

mean_ = y_true.mean()
SS_res = np.sum((y_true - y_pred) ** 2)
SS_total = np.sum((y_true - mean_) ** 2)

r2 = 1 - (SS_res / SS_total)

print(r2, SS_res, SS_total, mean_)

0.989 0.11000000000000018 10.0 3.0
CPU times: user 183 μs, sys: 25 μs, total: 208 μs
Wall time: 195 μs


-----